### ISSUE TITLE
"virtualenv 12 required"

### ISSUE THREAD

**Issue by abh** [mesosphere/install-scripts#35]
The "mesos.box" vagrant box comes without virtualenv installed. Only virtualenv 1.11.x is available in the ubuntu packages, but the dcos-cli install script aborts saying it requires "virtualenv 12". It'd be spiffy to have the dcos requirements available in the mesos vagrant box.

**Comment by ssk2** [comment]
Hey @abh - where are you getting `mesos.box` from? The USB stick or downloads.mesosphere.io?

**Comment by ssk2** [comment]
I've updated at the box at https://downloads.mesosphere.io/demo/mesos.box, it'll take a little while for it to update. You can easily install the latest version of virtualenv directly from PyPI through `sudo pip install --upgrade virtualenv`.
